### ISSUE TITLE
Can't interact with the auth window

### ISSUE THREAD

**Issue by tardigrde** [Stuyk/altv-os-auth#1]
Hi! 

First of all thanks for this package, as well as all the killer packages you created in order to ease alt:v development!

I have a problem with the authentication. I cloned your repository, installed deps, and put the example snippets into your quickstart project. Here is the code:
```
alt.on('playerConnect', playerConnect);

function playerConnect(player) {
    alt.log(`${player.name} has connected to the server.`);

    showAuthWindow(player);

    alt.on("auth:Done", exitAuthWindow);
    
    alt.emitClient(player, 'chat:Init');
    const randomModelNumber = Math.floor(Math.random() * DEFAULT_CONFIG.RANDOM_PLAYER_MODELS.length);
    const randomModel = DEFAULT_CONFIG.RANDOM_PLAYER_MODELS[randomModelNumber];
    const randomPosition = randomPositionAround(DEFAULT_CONFIG.SPAWN, DEFAULT_CONFIG.SPAWN_RANGE);

    // Set Model, Set Spawn, Send Message
    player.model = randomModel;
    player.spawn(randomPosition.x, randomPosition.y, randomPosition.z, 0);
    player.send(`Welcome to the server!`);
}
function showAuthWindow(player) {
  alt.emitClient(player, "auth:Open");
  alt.log(`${player.name} has connected!`);
}

function exitAuthWindow(player, id, username, email) {
  alt.emitClient(player, "auth:Exit");
  alt.log(`${player.name} has authenticated!`);
  alt.log(`Their Database ID is: ${id}`);
}
```
When I open the client, the auth window is shown, then I immediately get this: WARNING message:
```
[19:10:20] Player has connected!
[19:10:20][Warning] Event handler at base:file:///C:/codeing/gta/resources/base/server/events/playerConnect.js:7 was too long 13ms
```
Is this have to be awaited? I'm, not totally sure if this should be syncronous or async?

But the real problem of mine is that I cannot interact with the auth window. I can't click and type in the fields, nor can I click any of the buttons.

Can you give me a hint, what am I doing wrong? 

Thanks in advance!

**Comment by Stuyk** [comment]
```
alt.on("auth:Done", exitAuthWindow);
```

This should not be in playerConnect.
What you're doing here is creating multiple events that are being called multiple times.
Each time a player connects you are creating another `auth:Done` event.

You should also not be initializing chat until they are done authorizing.

```
 alt.emitClient(player, 'chat:Init');
```

Because you are initializing the authorization window before you are initializing chat. That means that you are creating a cursor for the Authorization window and then its immediately being unfocused because you're initializing chat.

Only initialize other webviews or create other webviews after the Authorization process. Which is the `"auth:Done"` event.

**Comment by Stuyk** [comment]
Mark this as closed when you understand.

**Comment by tardigrde** [comment]
I think I got it! Gonna try it tomorrow! 

I'm closing the issue, thanks a lot!
